### ISSUE TITLE
feat: integracion de la capa de servicio a uno de los controllers de los estudiantes

### ISSUE THREAD

**Issue by elialm7** [Fabrica-de-Desarrollo-CE-FPUNE/bqs-service#26]
En relacion con la issue #24 , esta issue busca integrar la capa de servicio con el controlador del estudiante
el cual se describe aqui :
https://github.com/Fabrica-de-Desarrollo-CE-FPUNE/bqs-service/blob/5d41962ab894f5ba5a874262d5b8eac94240fa22/src/api/controllers/estudianteController.ts#L5

**Comment by DDelvRoj** [comment]
ya estamos ya como para hacer el uso del mismo, tenemos todo

**Comment by elialm7** [comment]
@DDelvRoj  voy a pausar el desarrollo de este, integrar la nueva api y luego resumir o talvez cerrar esta issue.

**Comment by elialm7** [comment]
voy a trabajar por este, tratar de tener todo integrado funcionando
